// This file is autogenerated by scripts/generate_manifest.ts
// It ensures Deno Deploy Classic includes your modules in the bundle.

export * as index from "./index/mod.ts";
export * as ssr from "./ssr/mod.ts";
