brand: Fastro
logo: https://fastro.deno.dev/fastro.svg
title: The Next-Gen Content Management System
description: Experience the future of web development with our content management system. Built on Fastro Framework, Deno, and Preact, it delivers exceptional performance, scalability, and a smooth developer experience. Perfect for launching websites and apps, optimizing workflows, and enjoying seamless collaboration.
icon: https://fastro.deno.dev/favicon.ico
image: https://fastro.deno.dev/fastro.png
keywords: 
  - Fastro
  - CMS 
  - Content Management System 
  - Deno
  - Preact 
  - Web Development 
  - High Performance 
  - Scalability
  - Developer Experience
social:
  twitter: denofastro
  github: denofastro
  discord: denofastro
  youtube: denofastro
  facebook: denofastro
  instagram: denofastro
  linkedin: denofastro
  reddit: denofastro
  tiktok: denofastro
  telegram: denofastro
