name: bench
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  hello_bench:
    name: "Hello, bench!"
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: homestead
      DB_USER: root
      DB_PASSWORD: root

    permissions:
      id-token: write
      contents: write
      packages: write

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: test
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Setup PostgreSQL
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE USER root WITH PASSWORD 'root';"
          PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE homestead OWNER root;"
          PGPASSWORD=postgres psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE homestead TO root;"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Oha
        uses: baptiste0928/cargo-install@v1
        with:
          crate: oha
          version: 1.1.0

      - name: Generate internal benchmarks
        run: GITHUB_CLIENT_ID=${{ vars.GH_CLIENT_ID }} GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} deno task bench

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -d $GITHUB_REF_NAME
          git tag $GITHUB_REF_NAME
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true

      - name: Run Build
        run: GITHUB_CLIENT_ID=${{ vars.GH_CLIENT_ID }} GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fastro
          entrypoint: modules/app/main.ts
