name: merge
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno lint --unstable-kv core
      - run: deno lint --unstable-kv examples

      - name: Run tests
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} deno task test

      - name: Generate report
        run: deno task coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./cov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
